### ISSUE TITLE
timeout字段似乎没有生效？

### ISSUE THREAD

**Issue by sologgfun** [aliyun/fc-docker#102]
请问环境变量里面的FC_TIMEOUT没有用吗，在代码里面也没有看到使用到的地方？（nodejs10）
`docker run --rm -v $(pwd):/code --env-file ./env.list aliyunfc/runtime-nodejs10 --handler "index.handler" --event '{"key" : "value"}'`
1.把其中env.list里面把FC_TIMEOUT改成1
2.把demo的index.js改成一个耗时5s函数
现象：设定了1的timeout后，依然耗时5s才返回

**Comment by rsonghuster** [comment]
建议不要单独使用 fc-docker， 直接使用 serverless-devs 工具吧 https://docs.serverless-devs.com/fc/command/local#local-invoke-%E5%91%BD%E4%BB%A4
