### ISSUE TITLE
Running aliyunfc/runtime-python3.6 environment locally returns 'rsplit' error

### ISSUE THREAD

**Issue by zouyu-mb** [aliyun/fc-docker#110]
我有这个错误

[root@LO_all_test_192.168.2.59 10:28 /workspace/lambda-fc/funcraft/examples/nas/browser ]# docker run --rm -v $(pwd)/src:/code aliyunfc/runtime-python3.6 -e FC_HANDLER="index.handler" --initializer "index.initializer" --event '{"key" : "value"}'
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: 1baefb94-5cb2-411d-bc14-ccdbbd6ba620
2021-09-03T02:29:09.812Z 1baefb94-5cb2-411d-bc14-ccdbbd6ba620 [ERROR] {
"errorMessage": "'NoneType' object has no attribute 'rsplit'",
"errorType": "AttributeError",
"stackTrace": [
[
"File "/var/fc/runtime/python3/src/server.py"",
"line 233",
"in do_POST",
"valid_handler, request_handler = _get_handler(handler)"
],
[
"File "/var/fc/runtime/python3/src/server.py"",
"line 62",
"in _get_handler",
"(modname, fname) = handler.rsplit('.', 1)"
]
]
}
FC Invoke End RequestId: 1baefb94-5cb2-411d-bc14-ccdbbd6ba620, Error: Unhandled function error
{
"errorMessage": "'NoneType' object has no attribute 'rsplit'",
"errorType": "AttributeError",
"stackTrace": [
[
"File "/var/fc/runtime/python3/src/server.py"",
"line 233",
"in do_POST",
"valid_handler, request_handler = _get_handler(handler)"
],
[
"File "/var/fc/runtime/python3/src/server.py"",
"line 62",
"in _get_handler",
"(modname, fname) = handler.rsplit('.', 1)"
]
]
}

RequestId: 1baefb94-5cb2-411d-bc14-ccdbbd6ba620 Billed Duration: 11 ms Memory Size: 15810 MB Max Memory Used: 16 MB

**Comment by rsonghuster** [comment]
建议不要单独使用 fc-docker， 直接使用 serverless-devs 工具吧  https://docs.serverless-devs.com/fc/command/local#local-invoke-%E5%91%BD%E4%BB%A4
