### ISSUE TITLE
本地用docker如何断点调试云函数？

### ISSUE THREAD

**Issue by ChaiGuangJie** [aliyun/fc-docker#12]
aliyunfc/runtime-nodejs8 只能在本地执行云函数，如何断点调试?

**Comment by tanhe123** [comment]
可以参考这个 mr：https://github.com/aliyun/fun/pull/89

未来的一到两周内，我们会发布相关功能，改善本地运行、调试的体验。敬请期待。

**Comment by tanhe123** [comment]
新功能已发布：https://yq.aliyun.com/articles/672656
