### ISSUE TITLE
debian 9 镜像源是不支持了嘛？aliyunfc/runtime-python3.9:build-1.10.8 apt不能更新了 

### ISSUE THREAD

**Issue by MavPig** [aliyun/fc-docker#209]
```console
docker run -it --rm  aliyunfc/runtime-python3.9:build-1.10.8 /bin/bash                                                                                                           130 ↵
root@0f2ac1a13385:/code# apt update
Ign:1 http://mirrors.aliyun.com/debian stretch InRelease
Ign:2 http://mirrors.aliyun.com/debian stretch-updates InRelease
Ign:3 http://mirrors.aliyun.com/debian stretch-backports InRelease
Ign:4 http://mirrors.aliyun.com/debian-security stretch/updates InRelease
Err:5 http://mirrors.aliyun.com/debian stretch Release
  404  Not Found [IP: 111.170.130.228 80]
Err:6 http://mirrors.aliyun.com/debian stretch-updates Release
  404  Not Found [IP: 111.170.130.228 80]
Err:7 http://mirrors.aliyun.com/debian stretch-backports Release
  404  Not Found [IP: 111.170.130.228 80]
Err:8 http://mirrors.aliyun.com/debian-security stretch/updates Release
  404  Not Found [IP: 111.170.130.228 80]
Reading package lists... Done
E: The repository 'http://mirrors.aliyun.com/debian stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://mirrors.aliyun.com/debian stretch-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://mirrors.aliyun.com/debian stretch-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://mirrors.aliyun.com/debian-security stretch/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by fanzhe328** [comment]
aliyun 的源可能有些问题，先换其他源试一下吧

**Comment by fanzhe328** [comment]
> ```
> docker run -it --rm  aliyunfc/runtime-python3.9:build-1.10.8 /bin/bash                                                                                                           130 ↵
> root@0f2ac1a13385:/code# apt update
> Ign:1 http://mirrors.aliyun.com/debian stretch InRelease
> Ign:2 http://mirrors.aliyun.com/debian stretch-updates InRelease
> Ign:3 http://mirrors.aliyun.com/debian stretch-backports InRelease
> Ign:4 http://mirrors.aliyun.com/debian-security stretch/updates InRelease
> Err:5 http://mirrors.aliyun.com/debian stretch Release
>   404  Not Found [IP: 111.170.130.228 80]
> Err:6 http://mirrors.aliyun.com/debian stretch-updates Release
>   404  Not Found [IP: 111.170.130.228 80]
> Err:7 http://mirrors.aliyun.com/debian stretch-backports Release
>   404  Not Found [IP: 111.170.130.228 80]
> Err:8 http://mirrors.aliyun.com/debian-security stretch/updates Release
>   404  Not Found [IP: 111.170.130.228 80]
> Reading package lists... Done
> E: The repository 'http://mirrors.aliyun.com/debian stretch Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://mirrors.aliyun.com/debian stretch-updates Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://mirrors.aliyun.com/debian stretch-backports Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://mirrors.aliyun.com/debian-security stretch/updates Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```

aliyun 的源可能有些问题，先换其他源试一下吧

**Comment by MavPig** [comment]
> > ```
> > docker run -it --rm  aliyunfc/runtime-python3.9:build-1.10.8 /bin/bash                                                                                                           130 ↵
> > root@0f2ac1a13385:/code# apt update
> > Ign:1 http://mirrors.aliyun.com/debian stretch InRelease
> > Ign:2 http://mirrors.aliyun.com/debian stretch-updates InRelease
> > Ign:3 http://mirrors.aliyun.com/debian stretch-backports InRelease
> > Ign:4 http://mirrors.aliyun.com/debian-security stretch/updates InRelease
> > Err:5 http://mirrors.aliyun.com/debian stretch Release
> >   404  Not Found [IP: 111.170.130.228 80]
> > Err:6 http://mirrors.aliyun.com/debian stretch-updates Release
> >   404  Not Found [IP: 111.170.130.228 80]
> > Err:7 http://mirrors.aliyun.com/debian stretch-backports Release
> >   404  Not Found [IP: 111.170.130.228 80]
> > Err:8 http://mirrors.aliyun.com/debian-security stretch/updates Release
> >   404  Not Found [IP: 111.170.130.228 80]
> > Reading package lists... Done
> > E: The repository 'http://mirrors.aliyun.com/debian stretch Release' does not have a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > E: The repository 'http://mirrors.aliyun.com/debian stretch-updates Release' does not have a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > E: The repository 'http://mirrors.aliyun.com/debian stretch-backports Release' does not have a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > E: The repository 'http://mirrors.aliyun.com/debian-security stretch/updates Release' does not have a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > ```
> 
> aliyun 的源可能有些问题，先换其他源试一下吧

用官方源也是一样
```concole
docker run -it --rm  aliyunfc/runtime-python3.9:build-1.10.8 /bin/bash                                                             ✹feat/anle/serverless-ci
root@4deac09f81d2:/code# sed -i 's/mirrors.aliyun.com/deb.debian.org/g' /etc/apt/sources.list
root@4deac09f81d2:/code# apt update
Ign:1 http://deb.debian.org/debian stretch InRelease
Ign:2 http://deb.debian.org/debian stretch-updates InRelease
Ign:3 http://deb.debian.org/debian stretch-backports InRelease
Ign:4 http://deb.debian.org/debian-security stretch/updates InRelease
Err:5 http://deb.debian.org/debian stretch Release
  404  Not Found
Err:6 http://deb.debian.org/debian stretch-updates Release
  404  Not Found
Err:7 http://deb.debian.org/debian stretch-backports Release
  404  Not Found
Err:8 http://deb.debian.org/debian-security stretch/updates Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian-security stretch/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by MavPig** [comment]
update: debian 9源已经被archive了，需要使用`archive.debian.org`源
