### ISSUE TITLE
docker run --rm -v $(pwd):/code aliyunfc/runtime-python3.6 --handler "index.handler" --event '{"some": "event"}' 执行后有报错

### ISSUE THREAD

**Issue by Song2017** [aliyun/fc-docker#61]
```
上下文环境
songgsMac:~ songgs$ uname -a
Darwin songgsMac.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
songgsMac:~ songgs$ docker -v
Docker version 19.03.5, build 633a0ea
songgsMac:~ songgs$ cd _Git/fc-docker/demos/python3.6/
songgsMac:python3.6 songgs$ pwd
/Users/songgs/_Git/fc-docker/demos/python3.6

python3.6镜像错误信息
songgsMac:python3.6 songgs$ docker run --rm -v $(pwd):/code aliyunfc/runtime-python3.6 --handler "index.handler" --event '{"some": "event"}'
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: 9d9c1f44-abb7-4481-a599-b63d0e6bae18
2020-03-12T06:40:19.634Z 9d9c1f44-abb7-4481-a599-b63d0e6bae18 [ERROR] {
    "errorMessage": "'NoneType' object has no attribute 'rsplit'",
    "errorType": "AttributeError",
    "stackTrace": [
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 207",
            "in do_POST",
            "valid_handler, request_handler = _get_handler(handler)"
        ],
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 61",
            "in _get_handler",
            "(modname, fname) = handler.rsplit('.', 1)"
        ]
    ]
}
FC Invoke End RequestId: 9d9c1f44-abb7-4481-a599-b63d0e6bae18
{
    "errorMessage": "'NoneType' object has no attribute 'rsplit'",
    "errorType": "AttributeError",
    "stackTrace": [
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 207",
            "in do_POST",
            "valid_handler, request_handler = _get_handler(handler)"
        ],
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 61",
            "in _get_handler",
            "(modname, fname) = handler.rsplit('.', 1)"
        ]
    ]
}

RequestId: 9d9c1f44-abb7-4481-a599-b63d0e6bae18 	 Billed Duration: 36 ms  Memory Size: 1998 MB 	 Max Memory Used: 14 MB
```

**Comment by wss-git** [comment]
docker run --rm -it -e FC_HANDLER="index.handler" -v $(pwd):/code aliyunfc/runtime-python3.6 --initializer "index.initializer" --handler "index.handler" --event '{"key" : "value"}'

执行时添加一些环境变量 -e FC_HANDLER="index.handler" 再试试呢

**Comment by zouyu-mb** [comment]
我也有这个错误,
[root@LO_all_test_192.168.2.59 10:28 /workspace/lambda-fc/funcraft/examples/nas/browser ]# docker run --rm -v $(pwd)/src:/code aliyunfc/runtime-python3.6 -e FC_HANDLER="index.handler" --initializer "index.initializer" --handler "index.handler" --event '{"key" : "value"}'
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: 1baefb94-5cb2-411d-bc14-ccdbbd6ba620
2021-09-03T02:29:09.812Z 1baefb94-5cb2-411d-bc14-ccdbbd6ba620 [ERROR] {
    "errorMessage": "'NoneType' object has no attribute 'rsplit'",
    "errorType": "AttributeError",
    "stackTrace": [
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 233",
            "in do_POST",
            "valid_handler, request_handler = _get_handler(handler)"
        ],
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 62",
            "in _get_handler",
            "(modname, fname) = handler.rsplit('.', 1)"
        ]
    ]
}
FC Invoke End RequestId: 1baefb94-5cb2-411d-bc14-ccdbbd6ba620, Error: Unhandled function error
{
    "errorMessage": "'NoneType' object has no attribute 'rsplit'",
    "errorType": "AttributeError",
    "stackTrace": [
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 233",
            "in do_POST",
            "valid_handler, request_handler = _get_handler(handler)"
        ],
        [
            "File \"/var/fc/runtime/python3/src/server.py\"",
            "line 62",
            "in _get_handler",
            "(modname, fname) = handler.rsplit('.', 1)"
        ]
    ]
}

RequestId: 1baefb94-5cb2-411d-bc14-ccdbbd6ba620          Billed Duration: 11 ms          Memory Size: 15810 MB   Max Memory Used: 16 MB
