### ISSUE TITLE
无法支持http触发模式的raw-body（nodejs）

### ISSUE THREAD

**Issue by wangsijie** [aliyun/fc-docker#8]
使用nodejs8模式，选择http触发器后，将会使用raw-body这个自带的包，代码实际执行OK，但是在docker下提示

```
Cannot find module 'raw-body'
```

**Comment by tanhe123** [comment]
您需要首先在函数项目下 npm install raw-body。您可以参考：https://www.npmjs.com/package/raw-body

另外，如果您要本地调试函数可以使用我们的 Fun Local，参考这篇文章：https://yq.aliyun.com/articles/672656?spm=a2c4e.11153959.teamhomeleft.1.115948f2bVSnBa

**Comment by tanhe123** [comment]
fun 已支持 http trigger：https://github.com/aliyun/fun/releases/tag/v2.8.0
